arncv/Intima

public/pages/forum.html

Made the header and nav full width as screen 
Made the footer text visible

Solved issue #25

---

README.md

fixes #29 
Updated the contributors in README.md

Update contributors in README.md

---

public/pages/forum.html

I have added some additional questions to the forum.html file i.e. FAQ section.

Added potential queries in FAQ section

---

.vscode/settings.json
public/index.html

I have added the Volunteer Form Section to the Webpage

Added Volunteer Form Section

---

public/css/bot.css
public/pages/index.js
public/pages/intimabot.html
public/pages/style.css

Bot ui changed 

---

public/css/styles.css
public/index.html
public/scripts.js

#34 Feat: Added share link button in every learn more button popup. When it is shared and opened in a different system, it will automatically take you to the desired popup.

add open popup link button

---

public/css/styles.css
public/index.html

Fixed mobile responsiveness because of the image width on the home page.
Now working perfectly

Fixed the responsiveness on smaller devices

---

public/index.html

Updated the Intima Bot Section to display well and responsively in smaller screen

Intima Bot Frontend Update to adjust to mobile responsiveness  

---

public/css/styles.css

Debugged styling to make darkmode toggle img responsive on mobile

Nav darkmode responsiveness on mobile 

---

public/index.html
public/translation.js

I hope this time it should work

multi lang resolve conflict

---

new.env
public/index.html
public/scripts.js

This pr will close issue #6 as added parental guidance section with proper material.

Added a parental guidance section with proper material

---

public/pages/forum.html

I have made the forum navbar similar to home screen navbar and have also updated Resources link which was not working in forum navbar....
Now the resources link works that was in forum nav
The forum navbar looks like one on home screen

Forum Navbar updated issue#10

---

public/index.html

1. Added onclick route to the "Check Your Knowledge" button. Now activates link to quiz across entire button instead of only on the text portion of it.
2. Capitalized the "K" in knowledge to keep text styling consistent.

Improved Check Your Knowledge Button

---

public/pages/quiz.css

This will change Quiz UI to look more like the home page theme, issue #70

Change the UI of quiz page to look like home page

---

public/index.html
public/scripts.js

 add resources

---

public/css/styles.css
public/index.html
public/pages/forum.html
public/pages/parents.html

Fix #86 
This PR fixed two issues:
1. The dark mode in about section is not working
2. Dark mode should be active on page load

Fixed the dark mode not working and implemented it on page load

---

public/css/styles.css
public/index.html
public/translation.js

Added drop down menu for languages

---

public/css/bot.css
public/pages/intimabot.html

improved the chat page.
previous chat page: 
new chat page:
please add hactoberfest tag too.

enhance the UI of a chat page.

---

public/index.html
public/translation.js

feat: add hindi language support to all card

Add hindi to all card

---

public/pages/quiz.html
public/pages/quiz.js

added a new next button
fixed #72

next button added

---

public/pages/quiz.css
public/pages/quiz.html

the UI for the quiz page has been updated.
fixed #73

UI updated

---

new.env

Closes #96 
When I tried running locally using my API-key Intima bot, it worked fine, but this unnecessary new.env might be messing it up in production. Can someone verify if the API-key needs to be changed in production?

deleted new.env

---

public/pages/quiz.html
public/pages/quiz.js

Closes #108 
This PR does the following:
- Add 'Back' button to quiz,
- Fix 'Submit' button to appear at last question.
- New score logic: Instead of adding 1 when passing the question, when the quiz is submitted the score is calculated.
Evidence of Quiz:

feat: Add 'back' and 'submit' button to Quiz

---

public/pages/parents.html

I have added the content as described in the issue. I am attaching some screenshots here.
Please merge as hacktoberfest accepted. Thank You !!

#106 issue resolved | Add more content in Parent's section

---

public/css/styles.css
public/index.html

Please, have a look at issue I raised.
Made some cosmetic changes as well.
Issue: #113 
@arncv Please have a look.

Dark mode: Icon size consistency

---

public/index.html

Added new Get Help section, which have information about different organizations that offer sexual health services and resources.
Fixes: #102
**New Section**

Added section for Get Help
